sky:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    host: localhost
    port: 3306
    database: sky_take_out
    username: root
    password: 080100

  alioss:
    endpoint: t0pyj1lor.hd-bkt.clouddn.com
    access-key-id: ddnYhgLl4cztkvH1rsOcoWJFS0ablGELOTDezlcK
    access-key-secret: P5egwvj67MUC9GU3M7MhTGcSHCdk2OIwyM9MWHWO
    bucket-name: hunky
